! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : gckpp_Parameters.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Parameters

  USE gckpp_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 16 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 13 
! NFAM - Number of Prod/Loss Families
  INTEGER, PARAMETER :: NFAM = 1 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 7 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 3 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 27 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 14 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 1 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 1 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 14 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_CH4 = 1 
  INTEGER, PARAMETER :: ind_C12H4 = 2 
  INTEGER, PARAMETER :: ind_C12H3D = 3 
  INTEGER, PARAMETER :: ind_C13H4 = 4 
  INTEGER, PARAMETER :: ind_C13H3D = 5 
  INTEGER, PARAMETER :: ind_C14H4 = 6 
  INTEGER, PARAMETER :: ind_C14O = 7 
  INTEGER, PARAMETER :: ind_LCOH = 8 
  INTEGER, PARAMETER :: ind_LCCl = 9 
  INTEGER, PARAMETER :: ind_LCO1D = 10 
  INTEGER, PARAMETER :: ind_LCSOIL = 11 
  INTEGER, PARAMETER :: ind_LCDECAY = 12 
  INTEGER, PARAMETER :: ind_LCH4 = 13 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_FixedOH = 14 
  INTEGER, PARAMETER :: ind_FixedCl = 15 
  INTEGER, PARAMETER :: ind_FixedO1D = 16 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_FixedOH = 1 
  INTEGER, PARAMETER :: indf_FixedCl = 2 
  INTEGER, PARAMETER :: indf_FixedO1D = 3 

END MODULE gckpp_Parameters

