! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : gckpp_Monitor.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(16) :: SPC_NAMES = (/ &
     'CH4                             ','C12H4                           ','C12H3D                          ', & ! index 1 - 3
     'C13H4                           ','C13H3D                          ','C14H4                           ', & ! index 4 - 6
     'C14O                            ','LCOH                            ','LCCl                            ', & ! index 7 - 9
     'LCO1D                           ','LCSOIL                          ','LCDECAY                         ', & ! index 10 - 12
     'LCH4                            ','FixedOH                         ','FixedCl                         ', & ! index 13 - 15
     'FixedO1D                        ' /) ! index up to 16

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=32), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(27) :: EQN_NAMES = (/ &
     '    CH4 + FixedOH --> LCOH + LCH4                                                                   ', & ! index 1
     '    CH4 + FixedCl --> LCCl + LCH4                                                                   ', & ! index 2
     '   CH4 + FixedO1D --> LCO1D + LCH4                                                                  ', & ! index 3
     '              CH4 --> LCSOIL + LCH4                                                                 ', & ! index 4
     '  C12H4 + FixedOH --> LCOH                                                                          ', & ! index 5
     '  C12H4 + FixedCl --> LCCl                                                                          ', & ! index 6
     ' C12H4 + FixedO1D --> LCO1D                                                                         ', & ! index 7
     '            C12H4 --> LCSOIL                                                                        ', & ! index 8
     '  C13H4 + FixedOH --> LCOH                                                                          ', & ! index 9
     '  C13H4 + FixedCl --> LCCl                                                                          ', & ! index 10
     ' C13H4 + FixedO1D --> LCO1D                                                                         ', & ! index 11
     '            C13H4 --> LCSOIL                                                                        ', & ! index 12
     ' C12H3D + FixedOH --> LCOH                                                                          ', & ! index 13
     ' C12H3D + FixedCl --> LCCl                                                                          ', & ! index 14
     'C12H3D + FixedO1D --> LCO1D                                                                         ', & ! index 15
     '           C12H3D --> LCSOIL                                                                        ', & ! index 16
     ' C13H3D + FixedOH --> LCOH                                                                          ', & ! index 17
     ' C13H3D + FixedCl --> LCCl                                                                          ', & ! index 18
     'C13H3D + FixedO1D --> LCO1D                                                                         ', & ! index 19
     '           C13H3D --> LCSOIL                                                                        ', & ! index 20
     '  C14H4 + FixedOH --> C14O                                                                          ', & ! index 21
     '  C14H4 + FixedCl --> LCCl                                                                          ', & ! index 22
     ' C14H4 + FixedO1D --> LCO1D                                                                         ', & ! index 23
     '            C14H4 --> LCSOIL                                                                        ', & ! index 24
     '            C14H4 --> LCDECAY                                                                       ', & ! index 25
     '   C14O + FixedOH --> LCOH                                                                          ', & ! index 26
     '             C14O --> LCDECAY                                                                       ' /) ! index up to 27

  CHARACTER(LEN=32), PARAMETER, DIMENSION(1) :: FAM_NAMES = (/ &
     'LCH4                            ' /) ! index up to 1

! Begin inlined code from F90_DATA

! End inlined code from F90_DATA


END MODULE gckpp_Monitor
