! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-3.1.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : gckpp_Monitor.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(25) :: SPC_NAMES = (/ &
     'CH4                             ','C12_CH4                         ','C13_CH4                         ', & ! index 1 - 3
     'C14_CH4                         ','C1H4                            ','CH3D                            ', & ! index 4 - 6
     'CO                              ','CO2                             ','COfromCH4                       ', & ! index 7 - 9
     'COfromNMVOC                     ','CO2fromOH                       ','Dummy                           ', & ! index 10 - 12
     'PCO                             ','LCO                             ','LCH4                            ', & ! index 13 - 15
     'L12CH4                          ','L13CH4                          ','L14CH4                          ', & ! index 16 - 18
     'LC1H4                           ','LCH3D                           ','FixedOH                         ', & ! index 19 - 21
     'FixedO1D                        ','FixedCl                         ','DummyCH4                        ', & ! index 22 - 24
     'DummyNMVOC                      ' /) ! index up to 25

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=32), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(28) :: EQN_NAMES = (/ &
     '     CH4 + FixedOH --> CO + COfromCH4 + PCO + LCH4                                                  ', & ! index 1
     '    CH4 + FixedO1D --> Dummy + LCH4                                                                 ', & ! index 2
     '     CH4 + FixedCl --> Dummy + LCH4                                                                 ', & ! index 3
     '               CH4 --> Dummy + LCH4                                                                 ', & ! index 4
     ' C12_CH4 + FixedOH --> Dummy + L12CH4                                                               ', & ! index 5
     'C12_CH4 + FixedO1D --> Dummy + L12CH4                                                               ', & ! index 6
     ' C12_CH4 + FixedCl --> Dummy + L12CH4                                                               ', & ! index 7
     '           C12_CH4 --> Dummy + L12CH4                                                               ', & ! index 8
     ' C13_CH4 + FixedOH --> Dummy + L13CH4                                                               ', & ! index 9
     'C13_CH4 + FixedO1D --> Dummy + L13CH4                                                               ', & ! index 10
     ' C13_CH4 + FixedCl --> Dummy + L13CH4                                                               ', & ! index 11
     '           C13_CH4 --> Dummy + L13CH4                                                               ', & ! index 12
     ' C14_CH4 + FixedOH --> Dummy + L14CH4                                                               ', & ! index 13
     'C14_CH4 + FixedO1D --> Dummy + L14CH4                                                               ', & ! index 14
     ' C14_CH4 + FixedCl --> Dummy + L14CH4                                                               ', & ! index 15
     '           C14_CH4 --> Dummy + L14CH4                                                               ', & ! index 16
     '    C1H4 + FixedOH --> Dummy + LC1H4                                                                ', & ! index 17
     '   C1H4 + FixedO1D --> Dummy + LC1H4                                                                ', & ! index 18
     '    C1H4 + FixedCl --> Dummy + LC1H4                                                                ', & ! index 19
     '              C1H4 --> Dummy + LC1H4                                                                ', & ! index 20
     '    CH3D + FixedOH --> Dummy + LCH3D                                                                ', & ! index 21
     '   CH3D + FixedO1D --> Dummy + LCH3D                                                                ', & ! index 22
     '    CH3D + FixedCl --> Dummy + LCH3D                                                                ', & ! index 23
     '              CH3D --> Dummy + LCH3D                                                                ', & ! index 24
     '      CO + FixedOH --> CO2 + CO2fromOH + LCO                                                        ', & ! index 25
     '        DummyNMVOC --> CO + COfromNMVOC + PCO                                                       ', & ! index 26
     '          DummyCH4 --> CO + PCO                                                                     ', & ! index 27
     '                CO --> CO2 + CO2fromOH + LCO                                                        ' /) ! index up to 28

  CHARACTER(LEN=32), PARAMETER, DIMENSION(8) :: FAM_NAMES = (/ &
     'PCO                             ','LCO                             ','LCH4                            ', & ! index 1 - 3
     'L12CH4                          ','L13CH4                          ','L14CH4                          ', & ! index 4 - 6
     'LC1H4                           ','LCH3D                           ' /) ! index up to 8

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
