! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-3.1.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : gckpp_Function.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Function

  USE gckpp_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)
  !$OMP THREADPRIVATE(  A )

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Aggregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
!      Aout      - Optional argument to return equation rate constants
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot, Aout )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)
! Aout - Optional argument to return equation rate constants
  REAL(kind=dp), OPTIONAL :: Aout(NREACT)


! Computation of equation rates
  A(1) = RCT(1)*V(1)*F(1)
  A(2) = RCT(2)*V(1)*F(2)
  A(3) = RCT(3)*V(1)*F(3)
  A(4) = RCT(4)*V(1)
  A(5) = RCT(5)*V(2)*F(1)
  A(6) = RCT(6)*V(2)*F(2)
  A(7) = RCT(7)*V(2)*F(3)
  A(8) = RCT(8)*V(2)
  A(9) = RCT(9)*V(3)*F(1)
  A(10) = RCT(10)*V(3)*F(2)
  A(11) = RCT(11)*V(3)*F(3)
  A(12) = RCT(12)*V(3)
  A(13) = RCT(13)*V(4)*F(1)
  A(14) = RCT(14)*V(4)*F(2)
  A(15) = RCT(15)*V(4)*F(3)
  A(16) = RCT(16)*V(4)
  A(17) = RCT(17)*V(5)*F(1)
  A(18) = RCT(18)*V(5)*F(2)
  A(19) = RCT(19)*V(5)*F(3)
  A(20) = RCT(20)*V(5)
  A(21) = RCT(21)*V(6)*F(1)
  A(22) = RCT(22)*V(6)*F(2)
  A(23) = RCT(23)*V(6)*F(3)
  A(24) = RCT(24)*V(6)
  A(25) = RCT(25)*V(7)*F(1)
  A(26) = RCT(26)*F(5)
  A(27) = RCT(27)*F(4)
  A(28) = RCT(28)*V(7)

  !### Use Aout to return equation rates
  IF ( PRESENT( Aout ) ) Aout = A

! Aggregate function
  Vdot(1) = -A(1)-A(2)-A(3)-A(4)
  Vdot(2) = -A(5)-A(6)-A(7)-A(8)
  Vdot(3) = -A(9)-A(10)-A(11)-A(12)
  Vdot(4) = -A(13)-A(14)-A(15)-A(16)
  Vdot(5) = -A(17)-A(18)-A(19)-A(20)
  Vdot(6) = -A(21)-A(22)-A(23)-A(24)
  Vdot(7) = A(1)-A(25)+A(26)+A(27)-A(28)
  Vdot(8) = A(25)+A(28)
  Vdot(9) = A(1)
  Vdot(10) = A(26)
  Vdot(11) = A(25)+A(28)
  Vdot(12) = A(2)+A(3)+A(4)+A(5)+A(6)+A(7)+A(8)+A(9)+A(10)+A(11)+A(12)+A(13)+A(14)+A(15)+A(16)+A(17)+A(18)+A(19)+A(20)&
               &+A(21)+A(22)+A(23)+A(24)
  Vdot(13) = A(1)+A(26)+A(27)
  Vdot(14) = A(25)+A(28)
  Vdot(15) = A(1)+A(2)+A(3)+A(4)
  Vdot(16) = A(5)+A(6)+A(7)+A(8)
  Vdot(17) = A(9)+A(10)+A(11)+A(12)
  Vdot(18) = A(13)+A(14)+A(15)+A(16)
  Vdot(19) = A(17)+A(18)+A(19)+A(20)
  Vdot(20) = A(21)+A(22)+A(23)+A(24)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun_SPLIT - time derivatives of variables - Split form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
!      P_VAR     - Production term
!      D_VAR     - Destruction term
!      Aout      - Optional argument to return equation rate constants
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun_SPLIT ( V, F, RCT, Vdot, P_VAR, D_VAR, Aout )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)
! P_VAR - Production term
  REAL(kind=dp) :: P_VAR(NVAR)
! D_VAR - Destruction term
  REAL(kind=dp) :: D_VAR(NVAR)
! Aout - Optional argument to return equation rate constants
  REAL(kind=dp), OPTIONAL :: Aout(NREACT)


! Computation of equation rates
  A(1) = RCT(1)*V(1)*F(1)
  A(2) = RCT(2)*V(1)*F(2)
  A(3) = RCT(3)*V(1)*F(3)
  A(4) = RCT(4)*V(1)
  A(5) = RCT(5)*V(2)*F(1)
  A(6) = RCT(6)*V(2)*F(2)
  A(7) = RCT(7)*V(2)*F(3)
  A(8) = RCT(8)*V(2)
  A(9) = RCT(9)*V(3)*F(1)
  A(10) = RCT(10)*V(3)*F(2)
  A(11) = RCT(11)*V(3)*F(3)
  A(12) = RCT(12)*V(3)
  A(13) = RCT(13)*V(4)*F(1)
  A(14) = RCT(14)*V(4)*F(2)
  A(15) = RCT(15)*V(4)*F(3)
  A(16) = RCT(16)*V(4)
  A(17) = RCT(17)*V(5)*F(1)
  A(18) = RCT(18)*V(5)*F(2)
  A(19) = RCT(19)*V(5)*F(3)
  A(20) = RCT(20)*V(5)
  A(21) = RCT(21)*V(6)*F(1)
  A(22) = RCT(22)*V(6)*F(2)
  A(23) = RCT(23)*V(6)*F(3)
  A(24) = RCT(24)*V(6)
  A(25) = RCT(25)*V(7)*F(1)
  A(26) = RCT(26)*F(5)
  A(27) = RCT(27)*F(4)
  A(28) = RCT(28)*V(7)

  !### Use Aout to return equation rates
  IF ( PRESENT( Aout ) ) Aout = A

! Production function
  P_VAR(1) = 0
  P_VAR(2) = 0
  P_VAR(3) = 0
  P_VAR(4) = 0
  P_VAR(5) = 0
  P_VAR(6) = 0
  P_VAR(7) = A(1)+A(26)+A(27)
  P_VAR(8) = A(25)+A(28)
  P_VAR(9) = A(1)
  P_VAR(10) = A(26)
  P_VAR(11) = A(25)+A(28)
  P_VAR(12) = A(2)+A(3)+A(4)+A(5)+A(6)+A(7)+A(8)+A(9)+A(10)+A(11)+A(12)+A(13)+A(14)+A(15)+A(16)+A(17)+A(18)+A(19)+A(20)&
                &+A(21)+A(22)+A(23)+A(24)
  P_VAR(13) = A(1)+A(26)+A(27)
  P_VAR(14) = A(25)+A(28)
  P_VAR(15) = A(1)+A(2)+A(3)+A(4)
  P_VAR(16) = A(5)+A(6)+A(7)+A(8)
  P_VAR(17) = A(9)+A(10)+A(11)+A(12)
  P_VAR(18) = A(13)+A(14)+A(15)+A(16)
  P_VAR(19) = A(17)+A(18)+A(19)+A(20)
  P_VAR(20) = A(21)+A(22)+A(23)+A(24)

! Destruction function
  D_VAR(1) = RCT(1)*F(1)+RCT(2)*F(2)+RCT(3)*F(3)+RCT(4)
  D_VAR(2) = RCT(5)*F(1)+RCT(6)*F(2)+RCT(7)*F(3)+RCT(8)
  D_VAR(3) = RCT(9)*F(1)+RCT(10)*F(2)+RCT(11)*F(3)+RCT(12)
  D_VAR(4) = RCT(13)*F(1)+RCT(14)*F(2)+RCT(15)*F(3)+RCT(16)
  D_VAR(5) = RCT(17)*F(1)+RCT(18)*F(2)+RCT(19)*F(3)+RCT(20)
  D_VAR(6) = RCT(21)*F(1)+RCT(22)*F(2)+RCT(23)*F(3)+RCT(24)
  D_VAR(7) = RCT(25)*F(1)+RCT(28)
  D_VAR(8) = 0
  D_VAR(9) = 0
  D_VAR(10) = 0
  D_VAR(11) = 0
  D_VAR(12) = 0
  D_VAR(13) = 0
  D_VAR(14) = 0
  D_VAR(15) = 0
  D_VAR(16) = 0
  D_VAR(17) = 0
  D_VAR(18) = 0
  D_VAR(19) = 0
  D_VAR(20) = 0

  Vdot = P_VAR - D_VAR*V
      
END SUBROUTINE Fun_SPLIT

! End of Fun_SPLIT function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! CalcStoichNum - calculate stoichiometric numbers
!   Arguments :
!      StoichNum - Stoichiometric numbers
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE CalcStoichNum ( StoichNum )

! StoichNum - Stoichiometric numbers
  REAL(kind=dp) :: StoichNum(NVAR,NREACT)

  StoichNum(:,:) = 0.
  StoichNum(1,1) = -1
  StoichNum(1,2) = -1
  StoichNum(1,3) = -1
  StoichNum(1,4) = -1
  StoichNum(2,5) = -1
  StoichNum(2,6) = -1
  StoichNum(2,7) = -1
  StoichNum(2,8) = -1
  StoichNum(3,9) = -1
  StoichNum(3,10) = -1
  StoichNum(3,11) = -1
  StoichNum(3,12) = -1
  StoichNum(4,13) = -1
  StoichNum(4,14) = -1
  StoichNum(4,15) = -1
  StoichNum(4,16) = -1
  StoichNum(5,17) = -1
  StoichNum(5,18) = -1
  StoichNum(5,19) = -1
  StoichNum(5,20) = -1
  StoichNum(6,21) = -1
  StoichNum(6,22) = -1
  StoichNum(6,23) = -1
  StoichNum(6,24) = -1
  StoichNum(7,1) = 1
  StoichNum(7,25) = -1
  StoichNum(7,26) = 1
  StoichNum(7,27) = 1
  StoichNum(7,28) = -1
  StoichNum(8,25) = 1
  StoichNum(8,28) = 1
  StoichNum(9,1) = 1
  StoichNum(10,26) = 1
  StoichNum(11,25) = 1
  StoichNum(11,28) = 1
  StoichNum(12,2) = 1
  StoichNum(12,3) = 1
  StoichNum(12,4) = 1
  StoichNum(12,5) = 1
  StoichNum(12,6) = 1
  StoichNum(12,7) = 1
  StoichNum(12,8) = 1
  StoichNum(12,9) = 1
  StoichNum(12,10) = 1
  StoichNum(12,11) = 1
  StoichNum(12,12) = 1
  StoichNum(12,13) = 1
  StoichNum(12,14) = 1
  StoichNum(12,15) = 1
  StoichNum(12,16) = 1
  StoichNum(12,17) = 1
  StoichNum(12,18) = 1
  StoichNum(12,19) = 1
  StoichNum(12,20) = 1
  StoichNum(12,21) = 1
  StoichNum(12,22) = 1
  StoichNum(12,23) = 1
  StoichNum(12,24) = 1
  StoichNum(13,1) = 1
  StoichNum(13,26) = 1
  StoichNum(13,27) = 1
  StoichNum(14,25) = 1
  StoichNum(14,28) = 1
  StoichNum(15,1) = 1
  StoichNum(15,2) = 1
  StoichNum(15,3) = 1
  StoichNum(15,4) = 1
  StoichNum(16,5) = 1
  StoichNum(16,6) = 1
  StoichNum(16,7) = 1
  StoichNum(16,8) = 1
  StoichNum(17,9) = 1
  StoichNum(17,10) = 1
  StoichNum(17,11) = 1
  StoichNum(17,12) = 1
  StoichNum(18,13) = 1
  StoichNum(18,14) = 1
  StoichNum(18,15) = 1
  StoichNum(18,16) = 1
  StoichNum(19,17) = 1
  StoichNum(19,18) = 1
  StoichNum(19,19) = 1
  StoichNum(19,20) = 1
  StoichNum(20,21) = 1
  StoichNum(20,22) = 1
  StoichNum(20,23) = 1
  StoichNum(20,24) = 1
      
END SUBROUTINE CalcStoichNum

! End of CalcStoichNum function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gckpp_Function

